// <auto-generated />
using Cricket.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cricket.Migrations
{
    [DbContext(typeof(DBCricket))]
    [Migration("20240307121710_Cricket")]
    partial class Cricket
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Cricket.Models.Cricketer", b =>
                {
                    b.Property<long>("CricketerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<string>("CricketerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Fifties")
                        .HasColumnType("bigint");

                    b.Property<long>("Hundreds")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalODI")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalScore")
                        .HasColumnType("bigint");

                    b.HasKey("CricketerId");

                    b.ToTable("CricketerDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
